# Generated by Django 5.0.4 on 2024-04-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.CharField(default='', max_length=150, verbose_name='Short_name'),
        ),
    ]
